version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./:/app
    container_name: docker-node
    restart: always
    ports:
      - '8080:8080'
    command: npm run start
    env_file: .env